ersion: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-jessie
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv -f /tmp/docker/* /usr/local/bin
      - setup_remote_docker:
          version: 17.05.0-ce
      - add_ssh_keys:
          fingerprints: "ff:b1:40:d1:1b:8d:6c:a7:58:fa:6c:06:47:ff:58:c9"
      - run: bash deploy.bash
